PR to weather app (project complete)
vichuge/weather-app pull request #1
Opened 2021-04-20 21:51 UTC by vichuge

The application uses an API weather service to find the weather in different parts across the world.

2021-04-20 23:35 UTC, MahmoudBakr23 reviewed
# **INVALID 🛑**

<hr>

Hello there :)
Nice work submitting this project. However, it seems you forgot to set up your Linter. Please do so, then ask for another CRR to get this PR reviewed!
Remember that it's very important to maintain your repo and code professional and ready.

<hr>

Good luck and happy coding 👨‍💻💻

2021-04-21 15:32 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @vichuge! 👋 
You have done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [x] I am having trouble running your app. 
When trying to start your app from the command line I get the following error 👇🏾 
<img width="570" alt="Screen Shot 2021-04-21 at 5 20 34 PM" src="https://user-images.githubusercontent.com/48804258/115578806-e2aa4a00-a2c5-11eb-8224-efa6efb369e9.png">

When I go live from the index.html file, I am able to open the app but nothing happens after I click **Find Weather** 👇🏾 
![Screen Recording 2021-04-21 at 05 23 57 PM](https://user-images.githubusercontent.com/48804258/115579585-990e2f00-a2c6-11eb-9e95-e2bb12bb7a2a.gif)




****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-04-21 15:32 UTC, BrittanyBlake commented on src/index.js
> +async function getWeather(city = 'London') {
- [x] You are asked to use `ES6` syntax, so you should be using `arrow functions` here instead of the `function keyword.`

2021-04-21 16:54 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @vichuge :wave:

__I must commend your efforts so far in this project. However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] As mentioned by the last reviewer, running `npm start` still leads to the error mentioned previously. I believe this is so because the `webpack-dev-server` package is missing in your `devDependencies`. Kindly fix it.


**[ OPTIONAL CHANGES ]**

- [ ] Kindly add a toggle control to determine if the result will be shown in Celsius or Fahrenheit. 
- [ ] You should also make the page change its appearance based on the received data

_Note that these are supposed to be mandatory requirements. I only added it as optional because the last reviewer did not mention it. Therefore, it is strongly advised that you make the changes._

* * *
**Please make the required changes and submit another review request when you are done.**

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-21 16:54 UTC, teekaytech commented on README.md
> +- Here comes the website on the local machine.
The setup instruction in the Readme is not complete: you should add instructions on how the user can build for deployment, run a local server, etc.

2021-04-21 16:54 UTC, teekaytech commented on README.md
> +
Kindly deploy your application and add the live demo link to the Readme.

2021-04-21 20:36 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations @vichuge :tada: :clinking_glasses: 

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**

**Comment(s)**
- I mentioned in my last review, a couple of features to be implemented. It will be nice if you can consider adding these features before you move onto the next project. This is because those features are part of the project. I did not enforce them because the first reviewer did not mention them.

Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-21 20:36 UTC, merged